db:
  image: postgres:15
  environment:
    POSTGRES_USER:     ${DB_USER}     
    POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_DB:       ${DB_NAME}

backend:
  environment:
    DB_HOST:     db                  
    DB_PORT:     ${DB_PORT}
    DB_NAME:     ${DB_NAME}
    DB_USER:     ${DB_USER}
    DB_PASSWORD: ${DB_PASSWORD}
